server:
  port: 8082

spring:
  application:
    name: employee

  datasource:
    url: jdbc:postgresql://postgres.databases.svc.cluster.local:5432/hr_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    changelog: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/heimer-app

management:
  endpoints:
    web:
      exposure:
        include: health,info